version: '2.15.1'
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}
      - POSTGRES_USER=${LOCAL_DB_USER}
    image: postgres:14.5-alpine
    restart: always
    ports:
      # LOCAL_DB_PORT is the port you connect to locally
      - "${LOCAL_DB_PORT}:5432"